[package]
name = "tetris-bevy"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"

[dependencies.bevy]
version = "0.10"
default-features = false
features = [
	"bevy_asset",
	"bevy_sprite",
	"bevy_core_pipeline",
	"bevy_render",
	"wayland",
]
